export const WORLD_RAIN_AREA_METERS = 32;
export const WORLD_RAIN_MIN_HEIGHT_METERS = 2;
export const WORLD_RAIN_MAX_HEIGHT_METERS = 24;
export const WORLD_RAIN_FALL_SPEED_METERS_PER_SECOND = 18;
export const WORLD_RAIN_RECENTER_DISTANCE_METERS = 4;
export const WORLD_RAIN_GROUND_CACHE_RESOLUTION = 32;
export const WORLD_RAIN_GROUND_CACHE_ROWS_PER_FRAME = 4;
export const WORLD_RAIN_GROUND_CLIP_MARGIN_METERS = 0.14;
export const WORLD_RAIN_ACTIVE_THRESHOLD = 0.001;
export const WORLD_RAIN_RESPONSE_SECONDS = 0.55;
export const WORLD_RAIN_DESKTOP_CAPACITY = 1536;
export const WORLD_RAIN_COMPACT_CAPACITY = 768;
export const WORLD_RAIN_STREAK_LENGTH_METERS = 1.8;
export const WORLD_RAIN_STREAK_WIDTH_METERS = 0.035;
export const WORLD_RAIN_EDGE_FADE_METERS = 2.5;

export const WORLD_WETNESS_WETTING_SECONDS = 8;
export const WORLD_WETNESS_DRYING_SECONDS = 45;
export const WORLD_WETNESS_MAX_COLOR_DARKENING = 0.12;
export const WORLD_WETNESS_ROUGHNESS_FLOOR = 0.25;

export const WORLD_WATER_RAIN_RIPPLE_STRENGTH = 0.34;
export const WORLD_WATER_RAIN_RIPPLE_SCALE = 0.95;
export const WORLD_WATER_RAIN_RIPPLE_SPEED = 2.25;
export const WORLD_WATER_RAIN_RIPPLE_RING_WIDTH = 0.075;
export const WORLD_WATER_RAIN_RIPPLE_FADE_POWER = 0.7;

export const WORLD_WATER_CONTACT_CAPACITY_DESKTOP = 16;
export const WORLD_WATER_CONTACT_CAPACITY_COMPACT = 8;
