export const WORLD_WATER_CONTACT_CAPACITY_DESKTOP = 16;
export const WORLD_WATER_CONTACT_CAPACITY_COMPACT = 8;
export const WORLD_WATER_CONTACT_COVERAGE_THRESHOLD = 0.08;
export const WORLD_WATER_CONTACT_VERTICAL_TOLERANCE_METERS = 1.2;
export const WORLD_WATER_CONTACT_MIN_RADIUS_METERS = 0.08;
export const WORLD_WATER_CONTACT_MAX_RADIUS_METERS = 2.5;
export const WORLD_WATER_CONTACT_MAX_STRENGTH = 1.5;
export const WORLD_WATER_CONTACT_PROPAGATION_METERS_PER_SECOND = 2.8;
export const WORLD_WATER_CONTACT_DECAY_SECONDS = 1.1;
export const WORLD_WATER_CONTACT_MAX_AGE_SECONDS =
  WORLD_WATER_CONTACT_DECAY_SECONDS * 6;
